In [16]:
from interviews.db.database import SessionLocal, engine
from interviews.service.linkedin_service import add_contact
from sqlalchemy import inspect

import pandas as pd

db = SessionLocal()

In [17]:
df = pd.read_sql("select * from li.interview", db.bind)
df.head()

2026-03-02 17:17:58,548 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-03-02 17:17:58,550 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-03-02 17:17:58,552 INFO sqlalchemy.engine.Engine [cached since 2222s ago] {'table_name': 'select * from li.interview', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-03-02 17:17:58,554 INFO sqlalchemy.engine.Engine select * from li.interview
2026-03-02 17:17:58,555 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-03-02 17:17:58,558 INFO sqlalchemy.engine.Engine ROLLBACK

Empty DataFrame
Columns: [id, contact_id, notes, interview_date, created_at, fetched_at]
Index: []

In [18]:
inspector = inspect(engine)

# list schemas
# print(inspector.get_schema_names())

# list tables in your "li" schema
print(inspector.get_table_names(schema="li"))

2026-03-02 17:17:58,569 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-03-02 17:17:58,570 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
2026-03-02 17:17:58,571 INFO sqlalchemy.engine.Engine [cached since 2085s ago] {'param_1': 'r', 'param_2': 'p', 'relpersistence_1': 't', 'nspname_1': 'li'}
2026-03-02 17:17:58,573 INFO sqlalchemy.engine.Engine ROLLBACK
['contact', 'interview', 'interview_qa', 'question', 'answer_sentiment']

In [19]:
contact = add_contact("mary","project manager","Miele")

2026-03-02 17:17:58,600 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-03-02 17:17:58,603 INFO sqlalchemy.engine.Engine INSERT INTO li.contact (name, title, company, industry) VALUES (%(name)s, %(title)s, %(company)s, %(industry)s) RETURNING li.contact.id, li.contact.created_at, li.contact.fetched_at
2026-03-02 17:17:58,604 INFO sqlalchemy.engine.Engine [generated in 0.00084s] {'name': 'mary', 'title': 'project manager', 'company': 'Miele', 'industry': None}
2026-03-02 17:17:58,615 INFO sqlalchemy.engine.Engine COMMIT

In [20]:
df = pd.read_sql("select * from li.contact", db.bind)
df.head()

2026-03-02 17:18:50,406 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-03-02 17:18:50,410 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-03-02 17:18:50,413 INFO sqlalchemy.engine.Engine [cached since 2273s ago] {'table_name': 'select * from li.contact', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-03-02 17:18:50,417 INFO sqlalchemy.engine.Engine select * from li.contact
2026-03-02 17:18:50,418 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-03-02 17:18:50,423 INFO sqlalchemy.engine.Engine ROLLBACK

,id,name,title,company,industry,created_at,fetched_at
0,1,mary,project manager,Miele,None,2026-03-02 22:17:58.605158+00:00,2026-03-02 22:17:58.605158+00:00